### ISSUE TITLE
Unity versions supported

### ISSUE THREAD

**Issue by juandebravo** [opentok/opentok-unity-sample-windows#2]
Hi @robjperez !

Thanks for this! Could you please include in the README which Unity versions are supported?

Thanks!! ❤️

**Comment by robjperez** [comment]
Hi @juandebravo 

The sample has been tested with unity 2017.X versions only, I'll update the README file with that info.

However, it should work also in older versions, the most problematic part is the native render plugin, but the API used there should be compatible with at least 5.X versions. We haven't tested it there thought.

If you happen to test this in older versions of unity and it works, please report it here so we can update the README file

Thanks for the comment!

**Comment by robjperez** [comment]
Fixed in master branch
