### ISSUE TITLE
Create a multiparty sample with Unity

### ISSUE THREAD

**Issue by msach22** [opentok/opentok-unity-sample-windows#4]
Please thumbs up this issue if you would like to see a multiparty sample application that includes unity

**Comment by KenrickV-Hexaware** [comment]
Looking for a multiparty example too. Did you manage to get it working?

**Comment by msach22** [comment]
@KenrickV-Hexaware We currently don't have an ETA for the multiparty app so I created this issue to see the demand for it 😄.

Have you tried using the current sample and try to add multiple subscribers?

**Comment by cvasquez-github** [comment]
For multiparty you just need to subscribe to every stream you receive keeping a local list of streams: 
1-You have to instantiate a new Subscriber() object per each received stream (on mSession.StreamReceived)
2- Subscribe to it (mSession.Subscribe)
3- And add it to the local list. 
Then remove it from the list when the stream is dropped (on mSession.StreamDropped), and don't forget to unsubscribe to all of them and clear the list when you disconnect (on mSession.Disconnected).

**Comment by MichaelJolley** [comment]
Two years later and there doesn't seem to be a big interest. Closing this issue but we can open if demand increases.
