### ISSUE TITLE
steps to run Unity sample app 

### ISSUE THREAD

**Issue by monika-pant** [opentok/opentok-unity-sample-windows#5]
Hi , the current read me document is less declarative to be understood by beginners, could you please elaborate the steps to run the Unity sample , after creating and importing the DLLs.

**Comment by robjperez** [comment]
There is a specific README file for the unity sample part.
It lives here: https://github.com/opentok/opentok-unity-sample-windows/blob/master/UnityProject/OpenTok/README.md

Please take it a look and let us know if you are still having problem to run it
